/** Generated by zopia — do not edit by hand. */
import { z } from 'zod';

export const CreateUserSchema = z.object({ ["email"]: z.string().email(), ["role"]: z.string().default("viewer").optional() }) .strict();

export default CreateUserSchema;
