/** Generated by zopia — do not edit by hand. */
import { z } from 'zod';
import { makeApiConfig } from 'km-api';

export const traceProbe = makeApiConfig({
  method: "TRACE",
  pathShape: "/probe/{probeId}",
  operationId: "traceProbe",
  requestContentType: "application/vnd.zopia+json" as unknown as import('km-api').IRequestContentType,
  responseContentType: "application/vnd.zopia+json" as unknown as import('km-api').IResponseContentType,
  deprecated: 'YES',
  auth: "YES",
  summary: "Exercise km-api open unions",
  description: "",
  tags: ["#contract"],

  request: { body: z.object({ ["active"]: z.boolean() }).strict(),  params: z.object({ ["probeId"]: z.string() }), query: z.object({  }), headers: z.object({  }), cookies: z.object({  }) },
  response: { 419: z.string(), "default": z.object({  }).catchall(z.any()) },
});

export default traceProbe;
// Source: "km-api 0.4.1 Contract v1.0.0"
