import { mkdir, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { buildOpenApiOperationIR } from './openapi-ir';
import { extractOperationContracts } from './openapi-contracts';
import { jsonSchemaToZod } from './json-schema-to-zod';
import { planApiDocsFiles } from './api-docs-plan';
import type { ApiDocsMode } from './api-docs-layout';
import type { OpenApiDocument } from './openapi';
import { resolveOpenApiLocalRef } from './openapi-ref';

export interface GeneratedApiDocsFile { file: string; absolutePath: string; operationId: string; }
export interface GenerateApiDocsOptions { outputDir: string; mode?: ApiDocsMode; insertComponents?: boolean; useComponentAsReference?: boolean; }

function schemaCode(schema: unknown, name: string): string {
  const safeName = exportName(name);
  return jsonSchemaToZod(schema === undefined || schema === null ? true : schema as any, { rootName: safeName }).code.replace(/^const [^=]+ = /, '').replace(/;$/, '');
}
function quoteStatus(status: string): string { return /^\d+$/.test(status) ? status : JSON.stringify(status); }
function resolveObject(value: unknown, source: OpenApiDocument): any {
  let current = value; const seen = new Set<string>();
  while (current && typeof current === 'object' && !Array.isArray(current) && '$ref' in current) {
    const ref = (current as any).$ref;
    if (typeof ref !== 'string' || seen.has(ref)) return current;
    seen.add(ref); const target = resolveOpenApiLocalRef(source, ref);
    if (!target || typeof target !== 'object' || Array.isArray(target)) return current;
    current = { ...(target as any), ...Object.fromEntries(Object.entries(current as any).filter(([key]) => key !== '$ref')) };
  }
  return current;
}
function exportName(operationId: string): string {
  const parts = operationId.split(/[^A-Za-z0-9_$]+/).filter(Boolean);
  let name = parts.map((part, index) => index === 0 ? part : part[0].toUpperCase() + part.slice(1)).join('') || 'endpoint';
  if (!/^[A-Za-z_$]/.test(name)) name = `endpoint${name}`;
  if (['arguments', 'await', 'break', 'case', 'catch', 'class', 'const', 'continue', 'debugger', 'default', 'delete', 'do', 'else', 'enum', 'eval', 'export', 'extends', 'false', 'finally', 'for', 'function', 'if', 'implements', 'import', 'in', 'instanceof', 'interface', 'let', 'new', 'null', 'package', 'private', 'protected', 'public', 'return', 'static', 'super', 'switch', 'this', 'throw', 'true', 'try', 'typeof', 'var', 'void', 'while', 'with', 'yield'].includes(name)) name = `${name}Endpoint`;
  return name;
}
function renderComponent(name: string, schema: unknown, source: OpenApiDocument): string {
  const schemas = source.openapi ? source.components?.schemas ?? {} : source.definitions ?? {};
  const normalized = JSON.parse(JSON.stringify(schema, (_key, value) => typeof value === 'string' && (value.startsWith('#/components/schemas/') || value.startsWith('#/definitions/')) ? `#/$defs/${value.includes('/components/schemas/') ? value.slice('#/components/schemas/'.length) : value.slice('#/definitions/'.length)}` : value));
  const componentInput = typeof normalized === 'boolean' ? normalized : { ...(normalized as any), $defs: schemas };
  const converted = jsonSchemaToZod(componentInput as any, { rootName: `${exportName(name)}Schema` }).code.replace(/^const [^=]+ = /, '').replace(/;$/, '');
  return `/** Generated by zopia — do not edit by hand. */\nimport { z } from 'zod';\n\nexport const ${exportName(name)}Schema = ${converted};\n\nexport default ${exportName(name)}Schema;\n`;
}
function renderEndpoint(operation: any, source: OpenApiDocument): string {
  const ir = buildOpenApiOperationIR(source).find((candidate) => candidate.operationId === operation.operationId && candidate.path === operation.path && candidate.method.toLowerCase() === operation.method);
  if (!ir) throw new TypeError(`Unable to build operation IR: ${operation.operationId}`);
  const contracts = extractOperationContracts(ir);
  const params = (location: string) => contracts.parameters.filter((p) => p.in === location).map((p) => `${JSON.stringify(p.name)}: ${schemaCode(p.schema, `param${p.name.replace(/[^A-Za-z0-9]/g, '') || 'Value'}`)}${p.required ? '' : '.optional()'}`).join(', ');
  const request = `request: { body: ${contracts.requestBody ? schemaCode(contracts.requestBody.schema, 'requestBody') : 'z.any()'}, params: z.object({ ${params('path')} }), query: z.object({ ${params('query')} }), headers: z.object({ ${params('header')} }), cookies: z.object({ ${params('cookie')} }) }`;
  const response = contracts.responses.map((r) => `${quoteStatus(r.status)}: ${r.schema === undefined ? 'z.void()' : schemaCode(r.schema, `response${r.status.replace(/[^A-Za-z0-9]/g, '') || 'Default'}`)}`).join(', ');
  const responseContentType = contracts.responses.find((r) => r.contentType)?.contentType;
  const requestExamples: Record<string, unknown> = {};
  const requestBody = resolveObject(operation.operation.requestBody, source);
  const requestMedia = requestBody?.content ? Object.values(requestBody.content as Record<string, any>)[0] as any : undefined;
  if (requestMedia?.example !== undefined) requestExamples.default = { value: requestMedia.example };
  if (requestMedia?.examples && typeof requestMedia.examples === 'object') Object.assign(requestExamples, requestMedia.examples);
  const responseExamples: Record<string, unknown> = {};
  for (const [status, value] of Object.entries(operation.operation.responses ?? {})) {
    const raw = resolveObject(value, source);
    const media = raw && typeof raw === 'object' && (raw as any).content ? Object.values((raw as any).content)[0] as any : undefined;
    if (media?.example !== undefined) responseExamples[status] = { default: { value: media.example } };
    if (media?.examples && typeof media.examples === 'object') responseExamples[status] = media.examples;
    const legacyExamples = raw && typeof raw === 'object' ? (raw as any).examples : undefined;
    if (legacyExamples && typeof legacyExamples === 'object') responseExamples[status] = Object.fromEntries(Object.entries(legacyExamples).map(([contentType, value]) => [contentType, { value }]));
  }
  const examples = Object.keys(requestExamples).length || Object.keys(responseExamples).length ? `examples: ${JSON.stringify({ ...(Object.keys(requestExamples).length ? { request: requestExamples } : {}), ...(Object.keys(responseExamples).length ? { response: responseExamples } : {}) })},` : '';
  const opId = operation.operationId;
  const exportId = exportName(opId);
  const tags = ir.tags;
  const auth = ir.security !== undefined && ir.security.length > 0 ? 'YES' : 'NO';
  const sourceName = `${source.info.title} v${source.info.version}`;
  return `/** Generated by zopia — do not edit by hand. */\nimport { z } from 'zod';\nimport { makeApiConfig } from 'km-api';\n\nexport const ${exportId} = makeApiConfig({\n  method: ${JSON.stringify(operation.method.toUpperCase())},\n  pathShape: ${JSON.stringify(operation.path)},\n  operationId: ${JSON.stringify(opId)},\n  ${contracts.requestBody ? `requestContentType: ${JSON.stringify(contracts.requestBody.contentType)},` : ''}\n  ${responseContentType ? `responseContentType: ${JSON.stringify(responseContentType)},` : ''}\n  ${ir.deprecated ? "deprecated: 'YES'," : ''}\n  auth: ${JSON.stringify(auth)},\n  summary: ${JSON.stringify(operation.operation.summary ?? '')},\n  description: ${JSON.stringify(operation.operation.description ?? '')},\n  tags: ${JSON.stringify(tags)},\n  ${examples}\n  ${request},\n  response: { ${response} },\n});\n\nexport default ${exportId};\n// Source: ${sourceName}\n`;
}

/** Generate the planned endpoint files on disk. Existing generated files are overwritten. */
export async function generateApiDocsFiles(input: OpenApiDocument | string, options: GenerateApiDocsOptions): Promise<GeneratedApiDocsFile[]> {
  if (!options || typeof options.outputDir !== 'string' || !options.outputDir) throw new TypeError('outputDir is required');
  const source = typeof input === 'string' ? JSON.parse(input) : input;
  if (options.useComponentAsReference && !options.insertComponents) throw new TypeError('useComponentAsReference requires insertComponents');
  const plans = planApiDocsFiles(source, options.mode ?? 'directory');
  const root = resolve(options.outputDir); const generated: GeneratedApiDocsFile[] = [];
  if (options.insertComponents) {
    const schemas = source.openapi ? source.components?.schemas ?? {} : source.definitions ?? {};
    const names = Object.keys(schemas).sort();
    const componentExports = new Map<string, string>();
    for (const name of names) {
      const componentExport = `${exportName(name)}Schema`;
      const previous = componentExports.get(componentExport);
      if (previous) throw new TypeError(`Component export name collision: ${previous} and ${name}`);
      componentExports.set(componentExport, name);
      if (!name || name === '.' || name === '..' || name.includes('/') || name.includes('\\') || name.includes('\0')) throw new TypeError(`Unsafe component name: ${name}`);
      const file = `components/${name}/index.ts`; const absolutePath = join(root, file);
      await mkdir(resolve(absolutePath, '..'), { recursive: true });
      await writeFile(absolutePath, renderComponent(name, schemas[name], source), 'utf8');
      generated.push({ file, absolutePath, operationId: name });
    }
    const barrel = names.map((name) => `export { ${exportName(name)}Schema } from './${name}/index';`).join('\\n') + (names.length ? '\\n' : '');
    const barrelPath = join(root, 'components/index.ts'); await mkdir(resolve(barrelPath, '..'), { recursive: true }); await writeFile(barrelPath, barrel, 'utf8');
  }
  for (const plan of plans) {
    const absolutePath = join(root, plan.file);
    await mkdir(resolve(absolutePath, '..'), { recursive: true });
    await writeFile(absolutePath, renderEndpoint(plan, source), 'utf8');
    generated.push({ file: plan.file, absolutePath, operationId: plan.operationId });
  }
  return generated;
}
