/**
 * 🧠 Generated exact tree types (S-95).
 *
 * Renders the `.zopia-tree.d.ts` declaration emitted beside every retained
 * manifest: a types-only artifact describing the **exact** nested shape the
 * runtime resolver (`createApiDocs`) builds and the **exact** flat record
 * `flattenApiDocs` returns, so consumers get precise IntelliSense — literal
 * path-segment keys, method leaves typed as the generated module's own
 * `makeApiConfig()` export, and typo-proof access (unknown keys are compile
 * errors). Nothing runtime is emitted; the file is pure declaration.
 *
 * Ordering and naming are shared with the runtime: entries sort through
 * `compareApiDocsEntries` and flat keys derive through `endpointExportName` /
 * `uniqueEndpointName` — the same rules as the generator's `export const`
 * names — so the declared types match the runtime objects by construction.
 */

import { apiDocsPathSegments, compareApiDocsEntries } from './api-docs-layout';
import { endpointExportName, uniqueEndpointName } from './api-docs-names';

/** File name of the generated exact-tree declaration, written beside the manifest. */
export const ZOPIA_TREE_TYPES_FILE = '.zopia-tree.d.ts';

/** One endpoint record the declaration is rendered from. */
export interface ApiDocsTreeTypePlan {
  /** Portable endpoint-module path relative to the tree root (POSIX, with `.ts`). */
  file: string;
  /** OpenAPI path template — the authority for the nested key chain. */
  path: string;
  /** Lowercase HTTP method — the leaf key. */
  method: string;
  /** Declared or deterministically derived operation identifier. */
  operationId: string;
}

/** Internal tree node while assembling the declaration: a branch, a method leaf, or both. */
interface TypeTreeNode {
  /** Child branches/leaves by key; insertion follows the deterministic entry order. */
  children?: Map<string, TypeTreeNode>;
  /** Module type reference when this node is (also) a method leaf. */
  leaf?: { module: string; exportName: string };
}

/** Import-free module type reference: `typeof import('<module>').<exportName>`. */
const typeReference = (module: string, exportName: string): string => `typeof import('${module}').${exportName}`;

/** Module specifier of one endpoint plan: the portable file path without the `.ts` extension. */
const moduleSpecifier = (file: string): string => `./${file.replace(/\.ts$/, '')}`;

/**
 * Render the `.zopia-tree.d.ts` declaration for one tree root.
 *
 * @param apis Endpoint records (path operations only — webhooks are not URL-path endpoints).
 * @returns The complete declaration file text: an `ApiDocsTree` type keyed by exact URL path segments with lowercase-method leaves, and an `ApiDocsFlat` type keyed by the derived endpoint names.
 */
export function renderApiDocsTreeTypes(apis: readonly ApiDocsTreeTypePlan[]): string {
  const sorted = [...apis].sort(compareApiDocsEntries);
  const root: TypeTreeNode = {};
  for (const api of sorted) {
    let node: TypeTreeNode = root;
    for (const segment of apiDocsPathSegments(api.path)) {
      let child = node.children?.get(segment);
      if (!child) {
        child = {};
        (node.children ??= new Map<string, TypeTreeNode>()).set(segment, child);
      }
      node = child;
    }
    (node.children ??= new Map<string, TypeTreeNode>()).set(api.method, { leaf: { module: moduleSpecifier(api.file), exportName: endpointExportName(api.operationId) } });
  }

  const renderNode = (node: TypeTreeNode, depth: number): string => {
    if (!node.children || node.children.size === 0) return 'Record<string, never>';
    const indent = '  '.repeat(depth);
    const lines: string[] = [];
    for (const [key, child] of node.children) {
      const childType = child.leaf
        ? child.children && child.children.size > 0
          // A path continuing below another path's method leaf: the key is both the
          // endpoint config and a deeper branch — the permissive intersection shape.
          ? `(${typeReference(child.leaf.module, child.leaf.exportName)} & ${renderNode(child, 1)})`
          : typeReference(child.leaf.module, child.leaf.exportName)
        : renderNode(child, depth + 1);
      lines.push(`${indent}  readonly ${JSON.stringify(key)}: ${childType};`);
    }
    return `{\n${lines.join('\n')}\n${indent}}`;
  };

  const flatLines: string[] = [];
  const used = new Set<string>();
  for (const api of sorted) {
    const key = uniqueEndpointName(endpointExportName(api.operationId), used);
    used.add(key);
    flatLines.push(`  readonly ${JSON.stringify(key)}: ${typeReference(moduleSpecifier(api.file), endpointExportName(api.operationId))};`);
  }

  return [
    '/**',
    ' * Generated by zopia — do not edit by hand.',
    ' *',
    ' * Exact types of this api-docs tree as loaded at runtime by the',
    ' * `createApiDocs()` / `flattenApiDocs()` helpers of the zopia `zopia/runtime`',
    ' * subpath (types-only: this file imports nothing beyond the tree itself):',
    ' *',
    " *   const apiDocs = await createApiDocs<ApiDocsTree>('./<this-tree>');   // nested: exact segments → method",
    ' *   const endpoints = flattenApiDocs<ApiDocsFlat>(apiDocs);             // flat: exact endpoint names',
    ' */',
    `export type ApiDocsTree = ${renderNode(root, 0)};`,
    '',
    `export type ApiDocsFlat = ${flatLines.length ? `{\n${flatLines.join('\n')}\n}` : 'Record<string, never>'};`,
    '',
  ].join('\n').replace(/[ \t]+$/gm, '');
}
