import { describe, expect, it } from 'vitest';
import { readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import ts from 'typescript';
import { openApiToApiDocs } from '../src';
import { createApiDocs, flattenApiDocs } from '../src/runtime';
import { renderApiDocsTreeTypes, ZOPIA_TREE_TYPES_FILE, type ApiDocsTreeTypePlan } from '../src/conversions/api-docs-tree-types';
import { useTemporaryDirectories } from './test-temporary-directories';

const temporaryDirectory = useTemporaryDirectories('zopia-tree-types-');
const repositoryRoot = join(fileURLToPath(import.meta.url), '..', '..');

/** Spec exercising nested segments, params, and multiple methods per item. */
const nestedSpec = {
  openapi: '3.0.3',
  info: { title: 'Types', version: '1' },
  paths: {
    '/users/{userId}': {
      parameters: [{ name: 'userId', in: 'path', required: true, schema: { type: 'string' } }],
      get: { operationId: 'getUser', responses: { '200': { description: 'ok' } } },
      patch: { operationId: 'updateUser', responses: { '200': { description: 'ok' } } },
    },
    '/health': { get: { operationId: 'getHealth', responses: { '204': { description: 'empty' } } } },
  },
};

describe('generated exact tree types (S-95)', () => {
  it('S-95: renders the exact nested and flat declaration deterministically', () => {
    const plans: ApiDocsTreeTypePlan[] = [
      { file: 'health/get/index.ts', path: '/health', method: 'get', operationId: 'getHealth' },
      { file: 'users/{userId}/patch/index.ts', path: '/users/{userId}', method: 'patch', operationId: 'updateUser' },
      { file: 'users/{userId}/get/index.ts', path: '/users/{userId}', method: 'get', operationId: 'getUser' },
    ];
    const rendered = renderApiDocsTreeTypes(plans);
    // Canonical order regardless of input order: segments, then method order (get before patch).
    expect(rendered).toBe([
      '/**',
      ' * Generated by zopia — do not edit by hand.',
      ' *',
      ' * Exact types of this api-docs tree as loaded at runtime by the',
      ' * `createApiDocs()` / `flattenApiDocs()` helpers of the zopia `zopia/runtime`',
      ' * subpath (types-only: this file imports nothing beyond the tree itself):',
      ' *',
      " *   const apiDocs = await createApiDocs<ApiDocsTree>('./<this-tree>');   // nested: exact segments → method",
      ' *   const endpoints = flattenApiDocs<ApiDocsFlat>(apiDocs);             // flat: exact endpoint names',
      ' */',
      'export type ApiDocsTree = {',
      '  readonly "health": {',
      '    readonly "get": typeof import(\'./health/get/index\').getHealth;',
      '  };',
      '  readonly "users": {',
      '    readonly "{userId}": {',
      '      readonly "get": typeof import(\'./users/{userId}/get/index\').getUser;',
      '      readonly "patch": typeof import(\'./users/{userId}/patch/index\').updateUser;',
      '    };',
      '  };',
      '};',
      '',
      'export type ApiDocsFlat = {',
      '  readonly "getHealth": typeof import(\'./health/get/index\').getHealth;',
      '  readonly "getUser": typeof import(\'./users/{userId}/get/index\').getUser;',
      '  readonly "updateUser": typeof import(\'./users/{userId}/patch/index\').updateUser;',
      '};',
      '',
    ].join('\n'));
    expect(rendered).toBe(renderApiDocsTreeTypes([...plans].reverse()));
    expect(rendered).not.toMatch(/[ \t]+$/m);
  });

  it('S-95: root paths nest methods at the top level and empty trees stay permissive', () => {
    const root = renderApiDocsTreeTypes([{ file: 'root/get/index.ts', path: '/', method: 'get', operationId: 'rootGet' }]);
    expect(root).toContain('export type ApiDocsTree = {\n  readonly "get": typeof import(\'./root/get/index\').rootGet;\n};');
    expect(root).toContain('readonly "rootGet": typeof import(\'./root/get/index\').rootGet;');
    const empty = renderApiDocsTreeTypes([]);
    expect(empty).toContain('export type ApiDocsTree = Record<string, never>;');
    expect(empty).toContain('export type ApiDocsFlat = Record<string, never>;');
  });

  it('S-95: flat keys mirror runtime flattenApiDocs names, including collision suffixes', async () => {
    const outputDir = await temporaryDirectory();
    await openApiToApiDocs({
      openapi: '3.1.0',
      info: { title: 'Collide', version: '1' },
      paths: {
        // Distinct operationIds that camelize to the same export name: get-a / get.a → getA.
        '/a': { get: { operationId: 'get-a', responses: { '200': { description: 'ok' } } } },
        '/b': { get: { operationId: 'getA', responses: { '200': { description: 'ok' } } } },
        '/c': { get: { operationId: 'get.a', responses: { '200': { description: 'ok' } } } },
      },
    }, { outDir: outputDir });
    const declaration = await readFile(join(outputDir, ZOPIA_TREE_TYPES_FILE), 'utf8');
    const flatBlock = declaration.slice(declaration.indexOf('export type ApiDocsFlat'));
    const declaredKeys = [...flatBlock.matchAll(/readonly "([A-Za-z0-9_$]+)": typeof import/g)].map((match) => match[1]);
    // The declaration's flat keys and the runtime record's keys are derived by the same shared rules.
    expect(declaredKeys).toEqual(['getA', 'getA2', 'getA3']);
    const endpoints = flattenApiDocs(await createApiDocs(outputDir));
    expect(Object.keys(endpoints)).toEqual(['getA', 'getA2', 'getA3']);
    expect(endpoints.getA.pathShape).toBe('/a');
  });

  it('S-95: paths continuing below a method leaf render the permissive intersection shape', () => {
    const rendered = renderApiDocsTreeTypes([
      { file: 'users/get/index.ts', path: '/users', method: 'get', operationId: 'listUsers' },
      { file: 'users/get-2/get/index.ts', path: '/users/get', method: 'get', operationId: 'echoUsers' },
    ]);
    expect(rendered).toContain("readonly \"get\": (typeof import('./users/get/index').listUsers & {");
    expect(rendered).toContain("readonly \"get\": typeof import('./users/get-2/get/index').echoUsers;");
  });

  it('S-95/R-711: the declaration is written beside the manifest in both layouts and every preset bucket', async () => {
    for (const options of [{}, { mode: 'flat' as const }, { preset: 'multi-tag' as const }, { preset: 'multi-server' as const }]) {
      const outputDir = await temporaryDirectory();
      await openApiToApiDocs({
        openapi: '3.0.3',
        info: { title: 'Layout', version: '1' },
        servers: [{ url: 'https://a.example.com' }, { url: 'https://b.example.com' }],
        paths: {
          '/pets/{petId}': { get: { operationId: 'listPets', tags: ['pets'], parameters: [{ name: 'petId', in: 'path', required: true, schema: { type: 'string' } }], responses: { '200': { description: 'ok' } } } },
          '/health': { get: { operationId: 'getHealth', servers: [{ url: 'https://b.example.com' }], responses: { '204': { description: 'empty' } } } },
        },
      }, { ...options, outDir: outputDir });
      if (options.preset) {
        for (const entry of await readdir(outputDir, { withFileTypes: true })) {
          if (!entry.isDirectory()) continue;
          const declaration = await readFile(join(outputDir, entry.name, ZOPIA_TREE_TYPES_FILE), 'utf8');
          expect(declaration, `${options.preset}/${entry.name}`).toContain('export type ApiDocsTree =');
        }
      } else {
        const declaration = await readFile(join(outputDir, ZOPIA_TREE_TYPES_FILE), 'utf8');
        if (options.mode === 'flat') expect(declaration).toContain("import('./pets-{petId}/get/index')");
        else expect(declaration).toContain("import('./pets/{petId}/get/index')");
        expect(declaration).toContain('readonly "listPets"');
      }
    }
  });

  it('S-95/D-06: the declaration follows the manifest lifecycle — disabled manifests drop it, regeneration refreshes it', async () => {
    const outputDir = await temporaryDirectory();
    const first = { openapi: '3.1.0', info: { title: 'T', version: '1' }, paths: { '/before': { get: { operationId: 'getBefore', responses: { '200': { description: 'ok' } } } } } } as const;
    await openApiToApiDocs(first as never, { outDir: outputDir });
    expect(await readFile(join(outputDir, ZOPIA_TREE_TYPES_FILE), 'utf8')).toContain('readonly "getBefore"');

    const changed = { ...first, paths: { '/after': { get: { operationId: 'getAfter', responses: { '200': { description: 'ok' } } } } } };
    await openApiToApiDocs(changed as never, { outDir: outputDir });
    const refreshed = await readFile(join(outputDir, ZOPIA_TREE_TYPES_FILE), 'utf8');
    expect(refreshed).toContain('readonly "getAfter"');
    expect(refreshed).not.toContain('getBefore');

    // Disabling manifests prunes the declaration together with the manifest file.
    await openApiToApiDocs(first as never, { outDir: outputDir, manifest: false });
    // Manifest and declaration are both pruned; the regenerated endpoint directory stays.
    expect((await readdir(outputDir)).sort()).toEqual(['before']);
  });

  it('S-95: a broken declaration is reported as a missing owned file (staleness)', async () => {
    const outputDir = await temporaryDirectory();
    const spec = { openapi: '3.1.0', info: { title: 'T', version: '1' }, paths: { '/x': { get: { operationId: 'xGet', responses: { '200': { description: 'ok' } } } } } };
    await openApiToApiDocs(spec as never, { outDir: outputDir });
    await rm(join(outputDir, ZOPIA_TREE_TYPES_FILE));
    const result = await openApiToApiDocs(spec as never, { outDir: outputDir });
    expect(result.warnings).toContainEqual(expect.objectContaining({ code: 'ZOPIA_WARN_STALE_TREE' }));
    expect(await readFile(join(outputDir, ZOPIA_TREE_TYPES_FILE), 'utf8')).toContain('xGet');
  });

  it('S-95: exact IntelliSense — correct access typechecks, typos are compile errors', async () => {
    const outputDir = await temporaryDirectory();
    await openApiToApiDocs(nestedSpec as never, { outDir: outputDir });

    const consumer = [
      "import { createApiDocs, flattenApiDocs } from 'zopia/runtime';",
      "import type { ApiDocsFlat, ApiDocsTree } from './.zopia-tree';",
      'export const apiDocs = await createApiDocs<ApiDocsTree>(\'.\');',
      // Exactness: pathShape is the literal "/users/{userId}", not string.
      "export const exactShape: '/users/{userId}' = apiDocs.users['{userId}'].get.pathShape;",
      'export const params = apiDocs.users[\'{userId}\'].get.request.params;',
      'export const endpoints = flattenApiDocs<ApiDocsFlat>(apiDocs);',
      "export const flatShape: '/users/{userId}' = endpoints.getUser.pathShape;",
      'export const health = endpoints.getHealth.method;',
      '',
    ].join('\n');
    const typo = [
      "import { createApiDocs, flattenApiDocs } from 'zopia/runtime';",
      "import type { ApiDocsFlat, ApiDocsTree } from './.zopia-tree';",
      'export const apiDocs = await createApiDocs<ApiDocsTree>(\'.\');',
      'export const wrongSegment = apiDocs.noSuchSegment;',
      'export const wrongMethod = apiDocs.users[\'{userId}\'].post;',
      'export const wrongEndpoint = flattenApiDocs<ApiDocsFlat>(apiDocs).noSuchEndpoint;',
      '',
    ].join('\n');
    await writeFile(join(outputDir, 'consumer.ts'), consumer);
    await writeFile(join(outputDir, 'typo.ts'), typo);

    const options: ts.CompilerOptions = {
      allowImportingTsExtensions: true,
      module: ts.ModuleKind.ESNext,
      moduleResolution: ts.ModuleResolutionKind.Bundler,
      noEmit: true,
      paths: {
        'zopia/runtime': [join(repositoryRoot, 'src', 'runtime.ts')],
        zod: [join(repositoryRoot, 'node_modules', 'zod', 'index.d.ts')],
        'km-api': [join(repositoryRoot, 'node_modules', 'km-api', 'build', 'types', 'index.d.ts')],
      },
      strict: true,
      target: ts.ScriptTarget.ES2022,
    };
    const program = ts.createProgram([join(outputDir, 'consumer.ts'), join(outputDir, 'typo.ts')], options);
    const diagnostics = ts.getPreEmitDiagnostics(program).filter((diagnostic) => diagnostic.category === ts.DiagnosticCategory.Error);
    const consumerErrors = diagnostics.filter((diagnostic) => diagnostic.file?.fileName === join(outputDir, 'consumer.ts'));
    const typoErrors = diagnostics.filter((diagnostic) => diagnostic.file?.fileName === join(outputDir, 'typo.ts'));

    // Correct access — including the literal pathShape assertions — compiles cleanly.
    expect(consumerErrors).toEqual([]);
    // Every typo is rejected: unknown segment, unknown method leaf, unknown flat key.
    const typoText = typoErrors.map((diagnostic) => ts.flattenDiagnosticMessageText(diagnostic.messageText, ' ')).join('\n');
    expect(typoErrors.length).toBeGreaterThanOrEqual(3);
    expect(typoText).toContain('noSuchSegment');
    expect(typoText).toContain("'post'");
    expect(typoText).toContain('noSuchEndpoint');
  }, 120_000);
});
