/** Generated by zopia — do not edit by hand. */
import { z } from 'zod';

export const UserSchema = z.object({ ["id"]: z.string().uuid(), ["email"]: z.string().email(), ["role"]: z.enum(["admin","viewer"]).optional(), ["nickname"]: z.nullable(z.string()).optional() }) .strict().meta({"title":"User","description":"A user account"});

export default UserSchema;
