/** Generated by zopia — do not edit by hand. */
import { z } from 'zod';

export const UserSchema = (() => { /**
 * User
 * A user account
 */
const UserSchema = z.object({ ["email"]: z.string().email(), ["id"]: z.string().uuid(), ["nickname"]: z.string().nullable().optional(), ["role"]: z.enum(["admin","viewer"]).optional() }).strict().meta({"title":"User","description":"A user account"}); return UserSchema; })();

export default UserSchema;
