/**
 * Generated by zopia — do not edit by hand.
 *
 * Exact types of this api-docs tree as loaded at runtime by the
 * `createApiDocs()` / `flattenApiDocs()` helpers of the zopia `zopia/runtime`
 * subpath (types-only: this file imports nothing beyond the tree itself):
 *
 *   const apiDocs = await createApiDocs<ApiDocsTree>('./<this-tree>');   // nested: exact segments → method
 *   const endpoints = flattenApiDocs<ApiDocsFlat>(apiDocs);             // flat: exact endpoint names
 */
export type ApiDocsTree = {
  readonly "health": {
    readonly "get": typeof import('./health/get/index').health;
  };
  readonly "users": {
    readonly "{userId}": {
      readonly "get": typeof import('./users/{userId}/get/index').getUser;
      readonly "patch": typeof import('./users/{userId}/patch/index').updateUser;
    };
  };
};

export type ApiDocsFlat = {
  readonly "health": typeof import('./health/get/index').health;
  readonly "getUser": typeof import('./users/{userId}/get/index').getUser;
  readonly "updateUser": typeof import('./users/{userId}/patch/index').updateUser;
};
