/** Generated by zopia — do not edit by hand. */
import { z } from 'zod';
import { makeApiConfig } from 'km-api';

export const health = makeApiConfig({
  method: "GET",
  pathShape: "/health",
  operationId: "health",



  auth: "NO",
  summary: "",
  description: "",
  tags: [],

  request: { body: z.any(),  params: z.object({  }), query: z.object({  }), headers: z.object({  }), cookies: z.object({  }) },
  response: { 204: z.void() },
});

export default health;
// Source: "Admin API v1.2.0"
