import { defineConfig, type DefaultTheme } from 'vitepress';
import versionData from './versions.generated.json' with { type: 'json' };

/**
 * Version switcher and per-version sidebars are generated by
 * `scripts/sync-content.mjs` into `versions.generated.json` (R-215) — never
 * hand-maintained. `latest` is served from the site root; each frozen
 * snapshot lives under `/vX.Y/`.
 */
const { latest, latestMinor, versions } = versionData;

const versionNav: DefaultTheme.NavItem = {
  text: latestMinor,
  items: [
    { text: `${latestMinor} (latest)`, link: '/guide/introduction' },
    ...versions.map((entry) => ({
      text: `v${entry.version}`,
      link: `/${entry.minor}/${entry.pages[0].section}/${entry.pages[0].slug}`,
    })),
    { text: 'All releases on GitHub', link: 'https://github.com/komeilm76/zopia/releases' },
  ],
};

const versionSidebars = Object.fromEntries(
  versions.map((entry) => [
    `/${entry.minor}/`,
    [
      {
        text: `zopia v${entry.version}`,
        collapsed: false,
        items: entry.pages.map((page) => ({ text: page.title, link: `/${entry.minor}/${page.section}/${page.slug}` })),
      },
      {
        text: `Latest (v${latest})`,
        collapsed: true,
        items: [
          { text: 'Introduction', link: '/guide/introduction' },
          { text: 'Installation', link: '/guide/installation' },
          { text: 'Quick start', link: '/guide/quick-start' },
          { text: 'CLI reference', link: '/guide/cli' },
        ],
      },
    ],
  ]),
);

/**
 * zopia documentation website.
 *
 * Deployed to the public `komeilm76/komeilm76.github.io` repository under
 * `/zopia/`, so `base` must stay `/zopia/` — see
 * `docs/development/14-website.md`.
 */
export default defineConfig({
  base: '/zopia/',
  srcDir: 'src',
  lang: 'en-US',
  title: 'zopia',
  titleTemplate: ':title · zopia',
  description: 'Type-safe OpenAPI, JSON Schema, and Zod conversion toolkit.',
  cleanUrls: true,
  lastUpdated: true,
  ignoreDeadLinks: false,
  srcExclude: ['**/README.md'],

  // Emits sitemap.xml so search engines can discover every version route.
  sitemap: { hostname: 'https://komeilm76.github.io/zopia/' },

  head: [
    ['link', { rel: 'icon', type: 'image/svg+xml', href: '/zopia/favicon.svg' }],
    ['meta', { name: 'theme-color', content: '#6d5efc' }],
    ['meta', { property: 'og:type', content: 'website' }],
    ['meta', { property: 'og:title', content: 'zopia — type-safe OpenAPI ↔ Zod toolkit' }],
    ['meta', { property: 'og:description', content: 'Generate type-safe endpoint code from OpenAPI, and regenerate the spec from the code.' }],
    ['meta', { property: 'og:url', content: 'https://komeilm76.github.io/zopia/' }],
  ],

  markdown: {
    lineNumbers: false,
    theme: { light: 'github-light', dark: 'github-dark' },
  },

  vite: {
    server: {
      host: '0.0.0.0',
      // The sandboxed live preview is proxied through an arbitrary host name.
      allowedHosts: true,
    },
  },

  themeConfig: {
    logo: undefined,
    siteTitle: 'zopia',

    nav: [
      { text: 'Guide', link: '/guide/introduction', activeMatch: '/guide/' },
      { text: 'Reference', link: '/reference/conversions', activeMatch: '/reference/' },
      { text: 'Changelog', link: '/changelog' },
      versionNav,
    ],

    sidebar: {
      ...versionSidebars,
      '/guide/': [
        {
          text: 'Getting started',
          collapsed: false,
          items: [
            { text: 'Introduction', link: '/guide/introduction' },
            { text: 'Installation', link: '/guide/installation' },
            { text: 'Quick start', link: '/guide/quick-start' },
          ],
        },
        {
          text: 'Using zopia',
          collapsed: false,
          items: [
            { text: 'CLI reference', link: '/guide/cli' },
            { text: 'Programmatic API', link: '/guide/programmatic-api' },
            { text: 'Configuration', link: '/guide/configuration' },
            { text: 'Runtime', link: '/guide/runtime' },
          ],
        },
        {
          text: 'Reference',
          collapsed: false,
          items: [
            { text: 'Conversions', link: '/reference/conversions' },
            { text: 'API docs format', link: '/reference/api-docs-format' },
            { text: 'Components', link: '/reference/components' },
            { text: 'Errors & warnings', link: '/reference/errors-and-warnings' },
            { text: 'Concepts', link: '/reference/concepts' },
          ],
        },
      ],
      '/reference/': [
        {
          text: 'Reference',
          collapsed: false,
          items: [
            { text: 'Conversions', link: '/reference/conversions' },
            { text: 'API docs format', link: '/reference/api-docs-format' },
            { text: 'Components', link: '/reference/components' },
            { text: 'Errors & warnings', link: '/reference/errors-and-warnings' },
            { text: 'Concepts', link: '/reference/concepts' },
          ],
        },
        {
          text: 'Guide',
          collapsed: true,
          items: [
            { text: 'Introduction', link: '/guide/introduction' },
            { text: 'Installation', link: '/guide/installation' },
            { text: 'Quick start', link: '/guide/quick-start' },
            { text: 'CLI reference', link: '/guide/cli' },
            { text: 'Programmatic API', link: '/guide/programmatic-api' },
            { text: 'Configuration', link: '/guide/configuration' },
            { text: 'Runtime', link: '/guide/runtime' },
          ],
        },
      ],
    },

    socialLinks: [
      { icon: 'github', link: 'https://github.com/komeilm76/zopia' },
      { icon: 'npm', link: 'https://www.npmjs.com/package/zopia' },
    ],

    search: {
      provider: 'local',
      options: {
        detailedView: true,
      },
    },

    editLink: {
      /**
       * Site routes do not mirror the source layout: `docs/user/cli.md` is
       * served as `/guide/cli`, so the `:path` placeholder would produce
       * `docs/user/guide/cli.md` — a 404 on every page. The mapping is done
       * here instead, with pure string operations only: VitePress serializes
       * this function into the client bundle, so it must not close over any
       * outer variable.
       */
      pattern: ({ filePath }) => {
        const edit = 'https://github.com/komeilm76/zopia/edit/main/';
        // Frozen snapshots are immutable (R-211) and carry `editLink: false`
        // in their frontmatter; this guard is the belt to that pair of braces.
        if (/^v\d+\.\d+\//.test(filePath)) return '';
        if (filePath === 'changelog.md') return `${edit}CHANGELOG.md`;
        if (filePath === 'index.md') return `${edit}website/src/index.md`;
        const source = filePath.replace(/^(?:guide|reference)\//, '').replace(/^introduction\.md$/, 'index.md');
        return `${edit}docs/user/${source}`;
      },
      text: 'Suggest changes to this page',
    },

    outline: { level: [2, 3], label: 'On this page' },

    docFooter: { prev: 'Previous', next: 'Next' },

    footer: {
      message: 'Released under the MIT License · Documentation generated from <code>docs/user/</code>',
      copyright: `© ${new Date().getFullYear()} komeilm76`,
    },
  },
});
