/** Generated by zopia — do not edit by hand. */
import { z } from 'zod';
import { makeApiConfig } from 'km-api';
import { UserSchema } from '../../../components/index';

export const getUser = makeApiConfig({
  method: "GET",
  pathShape: "/users/{userId}",
  operationId: "getUser",
  
  responseContentType: "application/json" as unknown as import('km-api').IResponseContentType,
  deprecated: 'YES',
  auth: "YES",
  summary: "Get a user",
  description: "Returns one user",
  tags: ["#users"],
  examples: JSON.parse("{\"response\":{\"200\":{\"default\":{\"value\":{\"email\":\"admin@example.test\",\"id\":\"22ccbc6a-436b-4b1c-9e64-7440ce63a90e\",\"role\":\"admin\"}}}}}"),
  request: { body: z.any(),  params: z.object({ ["userId"]: z.string().uuid() }), query: z.object({  }), headers: z.object({ ["X-Trace-Id"]: z.string().optional() }), cookies: z.object({  }) },
  response: { 200: UserSchema, 404: z.object({  }).passthrough() },
});

export default getUser;
// Source: "Admin API v1.2.0"
