/**
 * Generated by zopia — do not edit by hand.
 *
 * Exact types of this api-docs tree as loaded at runtime by the
 * `createApiDocs()` / `flattenApiDocs()` helpers of the zopia `zopia/runtime`
 * subpath (types-only: this file imports nothing beyond the tree itself):
 *
 *   const apiDocs = await createApiDocs<ApiDocsTree>('./<this-tree>');   // nested: exact segments → method
 *   const endpoints = flattenApiDocs<ApiDocsFlat>(apiDocs);             // flat: exact endpoint names
 */
export type ApiDocsTree = {
  readonly "probe": {
    readonly "{probeId}": {
      readonly "trace": typeof import('./probe/{probeId}/trace/index').traceProbe;
    };
  };
};

export type ApiDocsFlat = {
  readonly "traceProbe": typeof import('./probe/{probeId}/trace/index').traceProbe;
};
